import { sum } from "../util/array.mjs";
import { forage, water } from "./names.mjs";
import { sizeNames, sizes } from "./sizes.mjs";

function between(...sizes) {
  return sum(sizes) / sizes.length;
}

export const speciesDefinitions = {
  rabbit: {
    name: 'rabbit',
    diet: [forage.grass, forage.leaves, forage.seeds],
    fecundity: 2,
    speed: 4,
    fat: 5,
    size: sizes[sizeNames.small],
  },
  deer: {
    name: 'deer',
    diet: [forage.grass, forage.leaves, forage.fruit, forage.lichen],
    speed: 4,
    armor: 2,
    fat: 10,
    size: sizes[sizeNames.big],
  },
  mushroom: {
    name: 'mushroom',
    diet: [forage.carrion, forage.wood, forage.leaves],
    size: sizes[sizeNames.tiny],
  },
  squirrel: {
    name: 'squirrel',
    diet: [forage.nuts],
    speed: 3,
    fat: 0.4,
    size: sizes[sizeNames.tiny],
  },
  'flying-squirrel': {
    name: 'flying-squirrel',
    diet: [forage.nuts],
    speed: 4,
    flying: true,
    size: sizes[sizeNames.tiny],
  },
  ant: {
    name: 'ant',
    diet: [forage.leaves, forage.carrion, forage.grass],
    weapons: 1,
    armor: 1,
    size: sizes[sizeNames.fine],
  },
  'fire-ant': {
    name: 'fire-ant',
    diet: [forage.leaves, forage.carrion, forage.grass],
    weapons: 1,
    venom: 'venom',
    size: sizes[sizeNames.fine],
  },
  fly: {
    name: 'fly',
    diet: [forage.carrion, forage.fruit],
    speed: 2,
    flying: true,
    size: sizes[sizeNames.tiny],
  },
  slug: {
    name: 'slug',
    diet: [forage.leaves, forage.carrion, forage.fruit],
    fecundity: 2.5,
    speed: 1,
    size: sizes[sizeNames.tiny],
  },
  bear: {
    name: 'bear',
    diet: [forage.carrion, forage.fruit, forage.nuts, forage.seeds],
    speed: 4,
    weapons: 5,
    armor: 2,
    fat: 80,
    size: sizes[sizeNames.huge],
  },
  bison: {
    name: 'bison',
    diet: [forage.grass],
    armor: 5,
    fat: 30,
    size: sizes[sizeNames.huge],
  },
  fish: {
    name: 'fish',
    diet: [forage.algae],
    speed: 1,
    armor: 1,
    fat: 10,
    size: sizes[sizeNames.small],
  },
  yeast: {
    name: 'yeast',
    diet: [forage.carrion, forage.seeds],
    size: sizes[sizeNames.micro],
  },
  termite: {
    name: 'termite',
    diet: [forage.wood],
    armor: 1,
    size: sizes[sizeNames.fine],
  },
  fox: {
    name: 'fox',
    diet: [forage.carrion, forage.fruit],
    speed: 2,
    weapons: 2,
    armor: 2,
    fat: 5,
    size: sizes[sizeNames.small],
  },
  minnow: {
    name: 'minnow',
    diet: [forage.algae],
    speed: 1,
    armor: 1,
    fat: 1,
    size: sizes[sizeNames.tiny],
  },
  shrimp: {
    name: 'shrimp',
    diet: [forage.algae, forage.carrion],
    speed: 1,
    armor: 2,
    size: sizes[sizeNames.tiny],
  },
  caribou: {
    name: 'caribou',
    diet: [forage.lichen],
    armor: 3,
    fat: 20,
    size: sizes[sizeNames.big],
  },
  locust: {
    name: 'locust',
    diet: [forage.seeds],
    fecundity: 2,
    flying: true,
    size: sizes[sizeNames.tiny],
  },
  mantis: {
    name: 'mantis',
    diet: [forage.carrion, forage.grass],
    speed: 1,
    weapons: 2,
    size: between(sizes[sizeNames.fine], sizes[sizeNames.tiny]),
  },
  hawk: {
    name: 'hawk',
    diet: [forage.carrion, forage.seeds],
    speed: 6,
    weapons: 4,
    fat: 40,
    flying: true,
    size: sizes[sizeNames.small],
  },
  spider: {
    name: 'spider',
    diet: [forage.carrion],
    weapons: 2,
    speed: 2,
    reach: true, // Webs allow spiders to attack flying prey
    venom: 'venom',
    size: between(sizes[sizeNames.fine], sizes[sizeNames.tiny]),
  },
  'mini-giraffe': {
    name: 'mini-giraffe',
    diet: [forage.leaves],
    armor: 2,
    fat: 5,
    size: sizes[sizeNames.medium],
  },
  'mega-giraffe': {
    name: 'mega-giraffe',
    diet: [forage.leaves],
    armor: 5,
    fat: 20,
    size: sizes[sizeNames.giant],
  },
  ironshroom: {
    name: 'ironshroom',
    diet: [forage.carrion, forage.leaves],
    size: sizes[sizeNames.small],
    armor: 4,
  },
  stonelicker: {
    name: 'stonelicker',
    diet: [forage.lichen],
    size: sizes[sizeNames.small],
  },
  'biting-termite': {
    name: 'biting-termite',
    diet: [forage.wood, forage.carrion],
    weapons: 1,
    size: sizes[sizeNames.tiny],
  },
  'leafcutter-beetle': {
    name: 'leafcutter-beetle',
    diet: [forage.leaves],
    speed: 1,
    armor: 1,
    size: sizes[sizeNames.tiny],
  },
  cat: {
    name: 'cat',
    diet: [forage.carrion],
    speed: 3,
    weapons: 3,
    armor: 1,
    fat: 15,
    size: sizes[sizeNames.small],
  },
  wolf: {
    name: 'wolf',
    diet: [forage.carrion],
    speed: 2,
    weapons: 4,
    armor: 2,
    fat: 10,
    size: sizes[sizeNames.medium],
  },
  deathcap: {
    name: 'deathcap',
    diet: [forage.wood, forage.leaves],
    venom: 'venom',
    size: sizes[sizeNames.small],
  },
  rattlesnake: {
    name: 'rattlesnake',
    diet: [forage.carrion],
    speed: 3,
    weapons: 1,
    venom: 'venom',
    size: sizes[sizeNames.tiny],
  },
  bird: {
    name: 'bird',
    diet: [forage.fruit, forage.seeds],
    speed: 3,
    flying: true,
    size: sizes[sizeNames.small],
  },
  gnat: {
    name: 'gnat',
    diet: [forage.fruit],
    flying: true,
    size: sizes[sizeNames.fine],
  },
  frog: {
    name: 'frog',
    diet: [forage.carrion, forage.algae],
    speed: 2,
    weapons: 2,
    reach: true, // Tongue allows frogs to catch flying prey
    multikill: 2,
    size: sizes[sizeNames.tiny],
  },
  rat: {
    name: 'rat',
    diet: [forage.carrion, forage.seeds],
    speed: 2,
    weapons: 1,
    fat: 1,
    size: sizes[sizeNames.tiny],
  },
  caterpillar: {
    name: 'caterpillar',
    diet: [forage.leaves],
    venom: 'venom',
    fat: 1,
    size: sizes[sizeNames.tiny],
  },
  'toxic-nudibranch': {
    name: 'toxic-nudibranch',
    diet: [forage.lichen],
    venom: 'venom',
    size: sizes[sizeNames.tiny],
  },
  'dire-honey-badger': {
    name: 'dire-honey-badger',
    diet: [forage.carrion],
    speed: 1,
    weapons: 1,
    armor: 3,
    fat: 50,
    venom: 'anti-venom', // Honey badgers are resistant to venom, so they can eat venomous prey without being affected
    size: sizes[sizeNames.medium],
  },
  'lichen-mite': {
    name: 'lichen-mite',
    diet: [forage.lichen],
    armor: 1,
    venom: 'venom',
    size: sizes[sizeNames.small],
  },
  'winged-springtail': {
    name: 'winged-springtail',
    diet: [forage.lichen],
    venom: 'venom',
    flying: true,
    size: sizes[sizeNames.tiny],
  },
  plankton: {
    name: 'plankton',
    diet: [forage.algae],
    size: sizes[sizeNames.micro],
  },
  sardine: {
    name: 'sardine',
    diet: [forage.carrion],
    weapons: 1,

    multikill: 1,
    // Normally, you can hunt about 1 size-tier smaller.
    // Same size may max out daily hunger, usually 40-120% of daily cap.
    // 1 size down will only give ~10-30% of daily max hunger.
    // Multikill grants x4 as many max kills/day, which approximately lets them hunt 1 size tier smaller than usual, or more reliably max out daily hunger when hunting within the same size tier.
    // Multiple points stack multiplicatively and thus shift the effective minimum-huntable prey size additional size tiers each.

    fat: 5,
    size: sizes[sizeNames.tiny],
  },
};

export default speciesDefinitions;